services:
  backend:
    build: ./backend
    container_name: virtusa-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/banking_prediction:/app/banking_prediction
      - ./storage:/app/storage
      - ./logs/backend:/app/logs  
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata   
    command: >
      sh -c "mkdir -p /app/logs && python run_backend_services.py > /app/logs/backend.log 2>&1"

  frontend:
    build: ./frontend
    container_name: virtusa-frontend
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules  
      - ./logs/frontend:/app/logs  
    environment:
      - VITE_PORT=5173
      - TZ=Asia/Kolkata   
    command: >
      sh -c "mkdir -p /app/logs && npm run dev"

volumes:
  frontend_node_modules: